routes/web.php
<?php

// Landing Page
Route::get('/', 'MainPageController@index')->name('welcome');

// EveOnline Login Redirect Url
Route::get('auth/redirect', 'ConnectController@authUrl')->name('auth.redirect');

// EveOnline OAuth Callback
Route::get('auth/callback', 'ConnectController@callback')->name('auth.callback');

// Owner Middleware Routes
Route::group(['prefix' => 'owner', 'middleware' => ['auth', 'owner'], 'as' => 'owner.'], function() {
    Route::get('/', 'Owner\OwnerController@index')->name('index');
    Route::get('user/edit/{id}', 'Owner\OwnerController@edit')->name('user.edit');
    Route::post('user/update/{id}', 'Owner\OwnerController@update')->name('user.update');
});


//Show Bjobs Middleware Routes
Route::group(['prefix' => 'bjobs', 'middleware' => ['showbuilding','auth']], function() {
	Route::get('/', 'bjobsController@index')->name('index');
	Route::get('bjob/edit/{id}', 'bjobsController@edit')->name('bjob.edit');
	Route::post('bjob/update/{id}', 'bjobsController@update')->name('bjob.update');
	
	});

//Create Middleware Routes
Route::group(['middleware' => ['order','auth']], function() {
    Route::get('/bjobs/create', 'bjobsController@create');
	
	});
//Bastion Middleware Routes
Route::group(['middleware' => ['bastion','auth']], function() {
Route::get('/bastion', 'MainPageController@bastion');
	
	});

Route::get('test', function() {
    $esi = new \Sumbria\Esi\Esi;
    $esi->setAccessToken(generate_token());
    $character_id = auth()->user()->character_id;
    $industry_obj = new \Sumbria\Esi\Industry();
    $character_mining = $industry_obj->getCharacterMining($character_id);
    if (is_array($character_mining['data']) && count($character_mining['data']) > 0) {
        foreach ($character_mining['data'] as $chr_mining) {
            
        }
    }
});

//Changelog
Route::get('/changelog', 'MainPageController@changelog');

//Middleware to store jobs
Route::group(['middleware' => 'auth'], function() {
    Route::post('/bjobstore', 'bjobsController@store');
});

//Showing Jobs
Route::group(['middleware' => ['showbuilding','auth']], function() {
	Route::get('/bjobs/show', 'bjobsController@show');
});

//Showing Individual Jobs
Route::group(['middleware' => ['showbuilding','auth']], function() {
	Route::get('/bjobs/show/{id}', 'bjobsController@ushow');
});

//Deleting Jobs
Route::group(['middleware' => ['showbuilding','auth']], function() {
	Route::get('/bjobs/show/delete', 'bjobsController@destroy');
});

//Updating Job
Route::group(['middleware' => ['showbuilding','auth']], function() {
	Route::get('/bjobs/edit/update', 'bjobsController@update');
});
	
//Test Searching Jobs
Route::get('/item/{searchTerm}', 'bjobsController@lookupitemname');


//Application Routes
Route::get('/application', 'ApplicationController@index');
Route::get('/application/store', 'ApplicationController@store');


//Auth Routes
Auth::routes();

//User Dashboard
Route::get('/home', 'HomeController@index')->name('home');

//Submit Bug Reports
Route::get('/bugreport', 'MainPageController@bug');


//Not Authed For That Page
Route::get('/noauth', 'MainPageController@noauth')->name('noauth');

app/Http/Controllers/Owner/OwnerController.php
<?php

namespace App\Http\Controllers\Owner;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;

class OwnerController extends Controller {

    public function index() {
        $group = isset($_GET['group']) ? $_GET['group'] : 'all';
        if ($group == 'guest') {
            $users = User::where('group', 'guest')->paginate(20);
        } elseif ($group == 'member') {
            $users = User::where('alliance_id', '99004425')->paginate(20);
        } elseif ($group == 'blue') {
            $users = User::where('alliance_id', '1354830081')->paginate(20); 
		} elseif ($group == 'builder') {
            $users = User::where('group', 'builder')->paginate(20);
        } elseif ($group == 'admin') {
            $users = User::where('group', 'admin')->paginate(20);
        } else {
            $users = User::where('group', '!=', 'owner')->paginate(20);
        }
        return view('backend.owner.index', compact('users', 'group'));
    }

    public function edit($id) {
        $user = User::find($id);
        if ($user) {
            return view('backend.owner.edit', compact('user'));
        } else {
            session()->flash('alert-danger', 'Something went wrong. Please try again.');
            return redirect()->route('owner.index');
        }
    }

    public function update($id, Request $request) {
        $user = User::find($id);
        if ($user) {
            $user->group = $request->group;
            $user->save();
            session()->flash('alert-success', 'User group updated.');
            return redirect()->route('owner.user.edit', $id);
        } else {
            session()->flash('alert-danger', 'Something went wrong. Please try again.');
            return redirect()->route('owner.index');
        }
    }

}

resources/views/backend/owner/edit.blade.php
@extends('backend.layouts.main')
@section('title', 'Edit User')
@section('content')
<div class="row">
    <div class="col-md-6">
        <!--begin::Portlet-->
        @include('backend.common.flash')
        <div class="m-portlet m-portlet--tab">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <span class="m-portlet__head-icon m--hide">
                            <i class="la la-gear"></i>
                        </span>
                        <h3 class="m-portlet__head-text">
                            Edit ({{ $user->name }})
                        </h3>
                    </div>
                </div>
            </div>
            <!--begin::Form-->
            <form method="POST" action="{{ route('owner.user.update', $user->id) }}" class="m-form m-form--fit m-form--label-align-right">
                @csrf
                <div class="m-portlet__body">
                    <div class="form-group m-form__group">
                        <label>Change Group</label>
                        <select name="group" class="form-control m-input">
                            <option value="guest">Guest</option>
                            <option value="member">Member</option>
							<option value="member">Blue</option>
                            <option value="builder">Builder</option>
                            <option value="admin">Admin</option>
                        </select>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn btn-metal">Change Group</button>
                    </div>
                </div>
            </form>
            <!--end::Form-->			
        </div>
        <!--end::Portlet-->
    </div>
</div>
@endsection

resources/views/backend/owner/index.blade.php
@extends('backend.layouts.main')
@section('title', 'Dashboard')
@section('content')
<div class="row">
    <div class="col-xl-12">
        @include('backend.common.flash')
        <!--begin::Portlet-->
        <div class="m-portlet">
            <div class="m-portlet__head m-portlet__head--fit-">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Users
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                    <ul class="nav nav-pills nav-pills--brand m-nav-pills--align-right m-nav-pills--btn-pill m-nav-pills--btn-sm" role="tablist">
                        <li class="nav-item m-tabs__item">
                            <a class="nav-link m-tabs__link{{ $group == 'all' ? ' active':'' }}" href="{{ route('owner.index') }}" role="tab">
                                All
                            </a>
                        </li>
                        <li class="nav-item m-tabs__item">
                            <a class="nav-link m-tabs__link{{ $group == 'guest' ? ' active':'' }}" href="{{ route('owner.index') }}?group=guest" role="tab">
                                Guest
                            </a>
                        </li>
                        <li class="nav-item m-tabs__item">
                            <a class="nav-link m-tabs__link{{ $group == 'member' ? ' active':'' }}" href="{{ route('owner.index') }}?group=member" role="tab">
                                Member
                            </a>
                        </li>
						<li class="nav-item m-tabs__item">
                            <a class="nav-link m-tabs__link{{ $group == 'blue' ? ' active':'' }}" href="{{ route('owner.index') }}?group=blue" role="tab">
                                Blue
                            </a>
                        </li>
                        <li class="nav-item m-tabs__item">
                            <a class="nav-link m-tabs__link{{ $group == 'builder' ? ' active':'' }}" href="{{ route('owner.index') }}?group=builder" role="tab">
                                Builder
                            </a>
                        </li>
                        <li class="nav-item m-tabs__item">
                            <a class="nav-link m-tabs__link{{ $group == 'admin' ? ' active':'' }}" href="{{ route('owner.index') }}?group=admin" role="tab">
                                Admin
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="m-portlet__body">
                <!--begin::Section-->
                <div class="m-section">
                    <div class="m-section__content">
                        <table class="table m-table m-table--head-separator-primary">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Group</th>
                                    <th>Character ID</th>
                                    <th>Corporation ID</th>
                                    <th>Alliance ID</th>
                                    <th>Race ID</th>
                                    <th>Bloodline ID</th>
                                    <th>Gender</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ ucfirst($user->group) }}</td>
                                    <td>{{ $user->character_id }}</td>
                                    <td>{{ $user->corporation_id }}</td>
                                    <td>{{ $user->alliance_id }}</td>
                                    <td>{{ $user->race_id }}</td>
                                    <td>{{ $user->bloodline_id }}</td>
                                    <td>{{ $user->gender }}</td>
                                    <td><a href="{{ route('owner.user.edit', $user->id) }}" class="btn m-btn--square  btn-primary btn-sm">Edit</a></td>
                                </tr>
                                @endforeach
                                <tr>
                                    <td colspan="9"><span class="pull-right">{{ $users->appends(['group' => $group])->links() }}</span></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!--end::Section-->
            </div>
            <!--end::Form-->
        </div>
        <!--end::Portlet-->
    </div>
</div>
@endsection